// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: api/mergerapi.proto

package mergerapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Text_Format int32

const (
	Text_PLAIN    Text_Format = 0
	Text_MARKDOWN Text_Format = 1
)

// Enum value maps for Text_Format.
var (
	Text_Format_name = map[int32]string{
		0: "PLAIN",
		1: "MARKDOWN",
	}
	Text_Format_value = map[string]int32{
		"PLAIN":    0,
		"MARKDOWN": 1,
	}
)

func (x Text_Format) Enum() *Text_Format {
	p := new(Text_Format)
	*p = x
	return p
}

func (x Text_Format) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Text_Format) Descriptor() protoreflect.EnumDescriptor {
	return file_api_mergerapi_proto_enumTypes[0].Descriptor()
}

func (Text_Format) Type() protoreflect.EnumType {
	return &file_api_mergerapi_proto_enumTypes[0]
}

func (x Text_Format) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Text_Format.Descriptor instead.
func (Text_Format) EnumDescriptor() ([]byte, []int) {
	return file_api_mergerapi_proto_rawDescGZIP(), []int{0, 0}
}

type Media_Type int32

const (
	Media_AUDIO   Media_Type = 0
	Media_VIDEO   Media_Type = 1
	Media_FILE    Media_Type = 2
	Media_PHOTO   Media_Type = 3
	Media_STICKER Media_Type = 4
)

// Enum value maps for Media_Type.
var (
	Media_Type_name = map[int32]string{
		0: "AUDIO",
		1: "VIDEO",
		2: "FILE",
		3: "PHOTO",
		4: "STICKER",
	}
	Media_Type_value = map[string]int32{
		"AUDIO":   0,
		"VIDEO":   1,
		"FILE":    2,
		"PHOTO":   3,
		"STICKER": 4,
	}
)

func (x Media_Type) Enum() *Media_Type {
	p := new(Media_Type)
	*p = x
	return p
}

func (x Media_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Media_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_api_mergerapi_proto_enumTypes[1].Descriptor()
}

func (Media_Type) Type() protoreflect.EnumType {
	return &file_api_mergerapi_proto_enumTypes[1]
}

func (x Media_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Media_Type.Descriptor instead.
func (Media_Type) EnumDescriptor() ([]byte, []int) {
	return file_api_mergerapi_proto_rawDescGZIP(), []int{1, 0}
}

type Text struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Format Text_Format `protobuf:"varint,1,opt,name=format,proto3,enum=mergerapi.Text_Format" json:"format,omitempty"`
	Value  string      `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Text) Reset() {
	*x = Text{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mergerapi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Text) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Text) ProtoMessage() {}

func (x *Text) ProtoReflect() protoreflect.Message {
	mi := &file_api_mergerapi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Text.ProtoReflect.Descriptor instead.
func (*Text) Descriptor() ([]byte, []int) {
	return file_api_mergerapi_proto_rawDescGZIP(), []int{0}
}

func (x *Text) GetFormat() Text_Format {
	if x != nil {
		return x.Format
	}
	return Text_PLAIN
}

func (x *Text) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Media struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    Media_Type `protobuf:"varint,1,opt,name=type,proto3,enum=mergerapi.Media_Type" json:"type,omitempty"`
	Caption *string    `protobuf:"bytes,2,opt,name=caption,proto3,oneof" json:"caption,omitempty"`
	Spoiler bool       `protobuf:"varint,3,opt,name=spoiler,proto3" json:"spoiler,omitempty"`
	Url     string     `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *Media) Reset() {
	*x = Media{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mergerapi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Media) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Media) ProtoMessage() {}

func (x *Media) ProtoReflect() protoreflect.Message {
	mi := &file_api_mergerapi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Media.ProtoReflect.Descriptor instead.
func (*Media) Descriptor() ([]byte, []int) {
	return file_api_mergerapi_proto_rawDescGZIP(), []int{1}
}

func (x *Media) GetType() Media_Type {
	if x != nil {
		return x.Type
	}
	return Media_AUDIO
}

func (x *Media) GetCaption() string {
	if x != nil && x.Caption != nil {
		return *x.Caption
	}
	return ""
}

func (x *Media) GetSpoiler() bool {
	if x != nil {
		return x.Spoiler
	}
	return false
}

func (x *Media) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// INPUT:
type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CreatedAt int64   `protobuf:"varint,1,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Author    *string `protobuf:"bytes,2,opt,name=author,proto3,oneof" json:"author,omitempty"`
	IsSilent  bool    `protobuf:"varint,3,opt,name=isSilent,proto3" json:"isSilent,omitempty"`
	// Types that are assignable to Body:
	//
	//	*Request_Text
	//	*Request_Media
	Body isRequest_Body `protobuf_oneof:"body"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mergerapi_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_api_mergerapi_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_api_mergerapi_proto_rawDescGZIP(), []int{2}
}

func (x *Request) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Request) GetAuthor() string {
	if x != nil && x.Author != nil {
		return *x.Author
	}
	return ""
}

func (x *Request) GetIsSilent() bool {
	if x != nil {
		return x.IsSilent
	}
	return false
}

func (m *Request) GetBody() isRequest_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (x *Request) GetText() *Text {
	if x, ok := x.GetBody().(*Request_Text); ok {
		return x.Text
	}
	return nil
}

func (x *Request) GetMedia() *Media {
	if x, ok := x.GetBody().(*Request_Media); ok {
		return x.Media
	}
	return nil
}

type isRequest_Body interface {
	isRequest_Body()
}

type Request_Text struct {
	Text *Text `protobuf:"bytes,4,opt,name=text,proto3,oneof"`
}

type Request_Media struct {
	Media *Media `protobuf:"bytes,5,opt,name=media,proto3,oneof"`
}

func (*Request_Text) isRequest_Body() {}

func (*Request_Media) isRequest_Body() {}

// Message:
type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ReplyMsgId *string `protobuf:"bytes,2,opt,name=reply_msg_id,json=replyMsgId,proto3,oneof" json:"reply_msg_id,omitempty"`
	CreatedAt  int64   `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Author     *string `protobuf:"bytes,4,opt,name=author,proto3,oneof" json:"author,omitempty"`
	Client     string  `protobuf:"bytes,5,opt,name=client,proto3" json:"client,omitempty"`
	IsSilent   bool    `protobuf:"varint,6,opt,name=isSilent,proto3" json:"isSilent,omitempty"`
	// Types that are assignable to Body:
	//
	//	*Response_Text
	//	*Response_Media
	Body isResponse_Body `protobuf_oneof:"body"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_mergerapi_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_api_mergerapi_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_api_mergerapi_proto_rawDescGZIP(), []int{3}
}

func (x *Response) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Response) GetReplyMsgId() string {
	if x != nil && x.ReplyMsgId != nil {
		return *x.ReplyMsgId
	}
	return ""
}

func (x *Response) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Response) GetAuthor() string {
	if x != nil && x.Author != nil {
		return *x.Author
	}
	return ""
}

func (x *Response) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

func (x *Response) GetIsSilent() bool {
	if x != nil {
		return x.IsSilent
	}
	return false
}

func (m *Response) GetBody() isResponse_Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (x *Response) GetText() *Text {
	if x, ok := x.GetBody().(*Response_Text); ok {
		return x.Text
	}
	return nil
}

func (x *Response) GetMedia() *Media {
	if x, ok := x.GetBody().(*Response_Media); ok {
		return x.Media
	}
	return nil
}

type isResponse_Body interface {
	isResponse_Body()
}

type Response_Text struct {
	Text *Text `protobuf:"bytes,7,opt,name=text,proto3,oneof"`
}

type Response_Media struct {
	Media *Media `protobuf:"bytes,8,opt,name=media,proto3,oneof"`
}

func (*Response_Text) isResponse_Body() {}

func (*Response_Media) isResponse_Body() {}

var File_api_mergerapi_proto protoreflect.FileDescriptor

var file_api_mergerapi_proto_rawDesc = []byte{
	0x0a, 0x13, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x72, 0x61, 0x70, 0x69, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x72, 0x61, 0x70, 0x69,
	0x22, 0x6f, 0x0a, 0x04, 0x54, 0x65, 0x78, 0x74, 0x12, 0x2e, 0x0a, 0x06, 0x66, 0x6f, 0x72, 0x6d,
	0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x6d, 0x65, 0x72, 0x67, 0x65,
	0x72, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x52, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x21,
	0x0a, 0x06, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x12, 0x09, 0x0a, 0x05, 0x50, 0x4c, 0x41, 0x49,
	0x4e, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x4d, 0x41, 0x52, 0x4b, 0x44, 0x4f, 0x57, 0x4e, 0x10,
	0x01, 0x22, 0xc9, 0x01, 0x0a, 0x05, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x12, 0x29, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x6d, 0x65, 0x72, 0x67,
	0x65, 0x72, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x2e, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x07, 0x63, 0x61, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x07, 0x63, 0x61, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x70, 0x6f, 0x69, 0x6c, 0x65, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x70, 0x6f, 0x69, 0x6c, 0x65, 0x72, 0x12,
	0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72,
	0x6c, 0x22, 0x3e, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x55, 0x44,
	0x49, 0x4f, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x56, 0x49, 0x44, 0x45, 0x4f, 0x10, 0x01, 0x12,
	0x08, 0x0a, 0x04, 0x46, 0x49, 0x4c, 0x45, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x50, 0x48, 0x4f,
	0x54, 0x4f, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x54, 0x49, 0x43, 0x4b, 0x45, 0x52, 0x10,
	0x04, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x63, 0x61, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xc5, 0x01,
	0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1b, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x88, 0x01, 0x01, 0x12, 0x1a, 0x0a, 0x08, 0x69, 0x73, 0x53, 0x69, 0x6c, 0x65, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69, 0x73, 0x53, 0x69, 0x6c, 0x65, 0x6e,
	0x74, 0x12, 0x25, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x72, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x65, 0x78, 0x74,
	0x48, 0x00, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x28, 0x0a, 0x05, 0x6d, 0x65, 0x64, 0x69,
	0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x72,
	0x61, 0x70, 0x69, 0x2e, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x48, 0x00, 0x52, 0x05, 0x6d, 0x65, 0x64,
	0x69, 0x61, 0x42, 0x06, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x61,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x22, 0xa6, 0x02, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x25, 0x0a, 0x0c, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x5f, 0x6d, 0x73, 0x67, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x0a, 0x72, 0x65, 0x70, 0x6c,
	0x79, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1b, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x02, 0x52, 0x06, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x88, 0x01, 0x01, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x69, 0x73, 0x53, 0x69, 0x6c, 0x65, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x08, 0x69, 0x73, 0x53, 0x69, 0x6c, 0x65, 0x6e, 0x74, 0x12, 0x25, 0x0a, 0x04, 0x74, 0x65, 0x78,
	0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x72,
	0x61, 0x70, 0x69, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x48, 0x00, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x12, 0x28, 0x0a, 0x05, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x72, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x65, 0x64, 0x69,
	0x61, 0x48, 0x00, 0x52, 0x05, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x42, 0x06, 0x0a, 0x04, 0x62, 0x6f,
	0x64, 0x79, 0x42, 0x0f, 0x0a, 0x0d, 0x5f, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x5f, 0x6d, 0x73, 0x67,
	0x5f, 0x69, 0x64, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x32, 0x45,
	0x0a, 0x0b, 0x42, 0x61, 0x73, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x36, 0x0a,
	0x07, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x12, 0x2e, 0x6d, 0x65, 0x72, 0x67, 0x65,
	0x72, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x6d,
	0x65, 0x72, 0x67, 0x65, 0x72, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x1a, 0x42, 0x09, 0x4d, 0x65, 0x72, 0x67, 0x65, 0x72, 0x41,
	0x70, 0x69, 0x50, 0x01, 0x5a, 0x0b, 0x2e, 0x2f, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x72, 0x61, 0x70,
	0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_mergerapi_proto_rawDescOnce sync.Once
	file_api_mergerapi_proto_rawDescData = file_api_mergerapi_proto_rawDesc
)

func file_api_mergerapi_proto_rawDescGZIP() []byte {
	file_api_mergerapi_proto_rawDescOnce.Do(func() {
		file_api_mergerapi_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_mergerapi_proto_rawDescData)
	})
	return file_api_mergerapi_proto_rawDescData
}

var file_api_mergerapi_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_mergerapi_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_mergerapi_proto_goTypes = []interface{}{
	(Text_Format)(0), // 0: mergerapi.Text.Format
	(Media_Type)(0),  // 1: mergerapi.Media.Type
	(*Text)(nil),     // 2: mergerapi.Text
	(*Media)(nil),    // 3: mergerapi.Media
	(*Request)(nil),  // 4: mergerapi.Request
	(*Response)(nil), // 5: mergerapi.Response
}
var file_api_mergerapi_proto_depIdxs = []int32{
	0, // 0: mergerapi.Text.format:type_name -> mergerapi.Text.Format
	1, // 1: mergerapi.Media.type:type_name -> mergerapi.Media.Type
	2, // 2: mergerapi.Request.text:type_name -> mergerapi.Text
	3, // 3: mergerapi.Request.media:type_name -> mergerapi.Media
	2, // 4: mergerapi.Response.text:type_name -> mergerapi.Text
	3, // 5: mergerapi.Response.media:type_name -> mergerapi.Media
	4, // 6: mergerapi.BaseService.Connect:input_type -> mergerapi.Request
	5, // 7: mergerapi.BaseService.Connect:output_type -> mergerapi.Response
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_api_mergerapi_proto_init() }
func file_api_mergerapi_proto_init() {
	if File_api_mergerapi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_mergerapi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Text); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mergerapi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Media); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mergerapi_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_mergerapi_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_mergerapi_proto_msgTypes[1].OneofWrappers = []interface{}{}
	file_api_mergerapi_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*Request_Text)(nil),
		(*Request_Media)(nil),
	}
	file_api_mergerapi_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*Response_Text)(nil),
		(*Response_Media)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_mergerapi_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_mergerapi_proto_goTypes,
		DependencyIndexes: file_api_mergerapi_proto_depIdxs,
		EnumInfos:         file_api_mergerapi_proto_enumTypes,
		MessageInfos:      file_api_mergerapi_proto_msgTypes,
	}.Build()
	File_api_mergerapi_proto = out.File
	file_api_mergerapi_proto_rawDesc = nil
	file_api_mergerapi_proto_goTypes = nil
	file_api_mergerapi_proto_depIdxs = nil
}
